export { default as Navbar } from "./Navbar";
// export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as PopularServices } from "./PopularServices";
export { default as SectionHeading } from "./SectionHeading";
export { default as OurApp } from "./OurApp";
export { default as DownloadButtons } from "./DownloadButtons";
export { default as FAQ } from "./FAQ";
export { default as ContactUs } from "./ContactUs";
export { default as Reviews } from "./Reviews";
